name: Deploy to Oracle Cloud using Docker Hub and Podman

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OCI CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv python3-pip

        # Create a virtual environment for OCI CLI
        python3 -m venv oci_env
        source oci_env/bin/activate

        # Install OCI CLI inside the virtual environment
        pip install oci-cli
