name: Deploy to Oracle Cloud using Docker Hub and Podman

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OCI CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv python3-pip

        # Create a virtual environment for OCI CLI
        python3 -m venv oci_env
        source oci_env/bin/activate

        # Install OCI CLI inside the virtual environment
        pip install oci-cli

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        # Write the private key to a file
        echo "${{ secrets.ORACLE_PRIVATE_KEY }}" | base64 -d > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
    
        # Manually create the OCI config file
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ secrets.ORACLE_USER_OCID }}" >> ~/.oci/config
        echo "fingerprint=${{ secrets.ORACLE_FINGERPRINT }}" >> ~/.oci/config
        echo "tenancy=${{ secrets.ORACLE_TENANCY_OCID }}" >> ~/.oci/config
        echo "region=${{ secrets.ORACLE_REGION }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
        chmod 600 ~/.oci/config

