name: Deploy to Oracle Cloud using Docker Hub and Podman

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OCI CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv python3-pip

        # Create a virtual environment for OCI CLI
        python3 -m venv oci_env
        source oci_env/bin/activate

        # Install OCI CLI inside the virtual environment
        pip install oci-cli

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        # Encode the private key from secrets before using it
        echo "${{ secrets.ORACLE_PRIVATE_KEY }}" | base64 > ~/.oci/oci_api_key.pem.base64
        base64 -d ~/.oci/oci_api_key.pem.base64 > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        oci_env/bin/oci setup config --config-file ~/.oci/config --region ${{ secrets.ORACLE_REGION }} --key-file ~/.oci/oci_api_key.pem
      env:
        ORACLE_TENANCY_OCID: ${{ secrets.ORACLE_TENANCY_OCID }}
        ORACLE_USER_OCID: ${{ secrets.ORACLE_USER_OCID }}
        ORACLE_REGION: ${{ secrets.ORACLE_REGION }}
        ORACLE_COMPARTMENT_OCID: ${{ secrets.ORACLE_COMPARTMENT_OCID }}
        ORACLE_FINGERPRINT: ${{ secrets.ORACLE_FINGERPRINT }}
